#! /bin/bash

<<'COMMENT'
 * Script para facilitar a inicializacao de um container docker
 * @param  containerName  o nome do container a inicializar
COMMENT

container="$1"

if [ $# -eq 0 ]; then
    echo "Error! No arguments suplied. Please specify container name."
else
        #Check if container exists
        if [ ! "$(docker ps -a | grep -w $container)" ]; then
            echo "Error: No such container: $container"
        else
            # If container is alredy running, do nothing.
            RUNNING=$(docker inspect --format="{{.State.Running}}" $container 2>/dev/null)
            if [ "$RUNNING" == "true" ]; then
                echo "Container $container is already running..."
                docker exec -it $container /bin/bash
            else
                echo "Container $container exists. Starting container"
                docker start $container
                docker exec -it $container /bin/bash
            fi

        fi
  
fi